spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:~/spring-boot-h2-db

    driverClassName: org.h2.Driver
    username: sa
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
  # To access H2 console http://localhost:8080/h2-console
  h2:
    console:
      enabled: true